name: build-cutefish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd scripts
          sed -i -E 's/TARGET_UBUNTU_VERSION=(.*)/TARGET_UBUNTU_VERSION="jammy"/g' default_config.sh
          ./build.sh -
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cutefish-from-scratch
          path: |
            scripts/cutefish-from-scratch.iso
            scripts/image/md5sum.txt
